export const ActionTypes = {
  FETCH_LIST_REQUEST: 'FETCH_LIST_REQUEST',
  FETCH_MORE_REQUEST: 'FETCH_MORE_REQUEST',
  FETCH_LIST_SUCCESS: 'FETCH_LIST_SUCCESS',
  FETCH_LIST_ERROR: 'FETCH_LIST_ERROR',
  FETCH_BITCOIN_REQUEST: 'FETCH_BITCOIN_REQUEST',
  FETCH_BITCOIN_SUCCESS: 'FETCH_BITCOIN_SUCCESS',
  FETCH_BITCOIN_ERROR: 'FETCH_BITCOIN_ERROR',
};
